# Jonathan Cowan
# PA2, Section 010, 11/15/2021
# Makefile for PA2

build:
	g++ -Wall Pixel.cpp Header.cpp Image.cpp manip.cpp mainDriver.cpp  -o PA2

clean:
	rm -rf PA2

run: build
	./PA2 ClemsonPaw.ppm Disney.ppm
